### ISSUE TITLE
Cannot specify chain information in analysis functions

### ISSUE THREAD

**Issue by yunhuige** [essex-lab/grand#2]
Hi,

I have a simulated system that has two chains. When I define `ref_atoms` for `cluster_waters` function, I cannot define two atoms from both chains. Attached is the pdb file of the system and you can see residues in two chains have the same resid. So without specifying chain information, I don't think I can make the scripts understand my reference atom definition. But in the current version, I cannot specify chainID in these analysis functions.

I notice there is a function called `getReferenceAtomIndices` to deal with chain/resid/atom_id information. But both `write_sphere_traj` and `cluster_waters` do not use this function for reference atom definition. Maybe a quick fix of this could be make both functions use `getReferenceAtomIndices` so that it is possible to specify chainID as well?

[1ec0-ghosts.pdb.zip](https://github.com/essex-lab/grand/files/7349262/1ec0-ghosts.pdb.zip)

**Comment by olliemelling** [comment]
Hi,

Thanks for raising this - it is a good point that it is currently not possible to specify chains when clustering. The `getReferenceAtomIndices` function won't be possible as that is only accessible within a sampler object and clustering is often performed without a sampler object being created.

I have re-written the `cluster_waters` function in utils.py and attached the new script below so it should work now. Can you test and let me know and if it does I will do the same to `write_sphere_traj` and push it to github.

Many thanks,
Ollie
[utils.zip](https://github.com/essex-lab/grand/files/7364018/utils.zip)

**Comment by yunhuige** [comment]
Hi Ollie, 

I did several tests using your scripts on my simulations. I think it worked! Thanks!

Yunhui

**Comment by olliemelling** [comment]
Ok sounds good, I will make the same change to `write_sphere_traj` and will close this issue now but do let us know if you come across any further problems with this.

Thanks,
Ollie
