### ISSUE TITLE
Expand to other fragments?

### ISSUE THREAD

**Issue by 0ut0fcontrol** [essex-lab/grand#3]
Hi, can this module easily expand to other fragments?
I want to use GCMC for tasks like [SILCS](https://pubs.acs.org/doi/10.1021/acs.jcim.9b00210).

Thank you!

**Comment by WillGPoole** [comment]
Hi, this is something we are definitely looking at. We are aiming to publish in due course, but unfortunately it is not something that is ready for release yet. 

Thanks,

Will

**Comment by 0ut0fcontrol** [comment]
Thank you for your response.

I will keep watching this repo and looking forward to this function being implemented in `grand`.

Best,

Jincai
