### ISSUE TITLE
'No ghost water molecules left' error

### ISSUE THREAD

**Issue by dlukauskis** [essex-lab/grand#5]
I'm using the equilibration protocol from the BPTI example, with two UVT and NPT simulations, to equilibrate one of my systems. I'm getting a strange _grand_ error that stochstically pops up during the first UVT sim. 
```
2021-11-24 21:32:37,131 - ERROR: No ghost water molecules left, so insertion moves cannot occur - add more ghost waters
```

I'm using quite a large sphere (10 angstrom) and lots of ghosts (n = 15) to be on the safe side of getting all the waters right in the binding site. [Input and log files](https://github.com/essex-lab/grand/files/7601980/no_ghost_waters_left_example.zip) are here.

**Comment by dlukauskis** [comment]
This is just an issue with the number of ghosts, too few for a sphere of 10 angstrom - personal comms with @marleysamways . Will resubmit the sims with n = 150 to confirm this.

**Comment by olliemelling** [comment]
Hi @dlukauskis, 

Just to confirm that this is simply an issue with there not being enough ghost waters defined when the sampler object is created - 15 waters is unlikely to be sufficient for a sphere size of 10 A. The `uvt1-ghosts.txt` file lists the number of ghost waters available each time `sampler.report()` is called so you can use this as a guide as to whether the simulation is close to running out of ghost waters.

Setting `n=150` should mean there are more than enough ghost waters - can you just confirm this works for you and we can then close the issue.

Many thanks,
Ollie

**Comment by dlukauskis** [comment]
I can confirm this fixed the problem.
