### ISSUE TITLE
Running NVT MD on GCMC equilibrated structure

### ISSUE THREAD

**Issue by qyuan7** [essex-lab/grand#8]
Hello,

In the paper for grand (J. Chem. Inf. Model. 2020, 60, 10, 4436–4441), comparison were made between GCMC/MD and NVT MD on BPTI, where all steps of GCMC/MD workflow were replaced by NVT MD. I'm wondering would the result be any different if I GCMC/MD for equilibration first, and run NVT MD for the production run only, in order to reduce the computational cost? 

A related question would be: if all the GCMC moves in the GCMC/MD were rejected (especially during later stages of GCMC/MD when the ), would such GCMC/MD be of any different compared to an NVT MD?

Thanks very much,

Qi

**Comment by olliemelling** [comment]
Hi,

It depends on what you want information you want to gain from performing GCMC sampling. If you simply want to equilibrate a water network within a crystal structure (or similar initial structure) before running a classical MD simulation then equilibrating with GCMC/MD and running NVT production is fine. 

However, in many cases we see that bound water networks are dynamic and can impact protein/ligand conformations etc therefore it is often important to continue to sample the bound waters effectively during the production run, in which case it would make sense to run GCMC/MD for the whole simulation. You can alter the ratio of MD sampling to GCMC/MD sampling performed in the simulation to reflect how important you consider the water sampling to be.

If all GCMC moves are rejected then yes, it would be as if NVT MD sampling had been performed with no enhanced sampling.

Thanks,

Ollie
