### ISSUE TITLE
Do probabilities of insertion and deletion have to be equal? 

### ISSUE THREAD

**Issue by qyuan7** [essex-lab/grand#9]
Hi,

I noticed in the grand code and some of the papers that the attempt of insertion or deletion was determined with uniform probability, i.e. the probability of attempting insertion or deletion was both ~0.5 for a GC(NC)MC move. My question is that can I change the probability of insertion/deletion for a GC(NC)MC move during simulation, for example favouring water insertion with higher probability (or the other way round), will the difference in probabilities of insertion/deletion be wrong theoretically?

Thanks very much,

Qi

**Comment by olliemelling** [comment]
Hi Qi,

There are two ways you can potentially bias towards insertion/deletion moves in grand canonical simulations. One approach is to bias the probability of actually attempting an insertion or deletion move (which I think is what you are suggesting). This is theoretically possible, provided the biases are accounted for in the acceptance criteria. For example if you wanted to make insertion moves twice as likely as deletion moves, the acceptance probability of the insertion moves would have to be scaled accordingly (which may mean you don't end up observing the desired effect anyway). This is not implemented in grand so you would have to make these changes yourself in the code if you wanted to do this.

The other approach is to bias the acceptance probabilities of the moves (but still attempt insertions and deletions with equal probabilities). This can be done by changing the B-value (Adams parameter) where higher B-values reflect a higher chemical potential and therefore make insertion moves more likely to be accepted (and a higher average number of waters would likely be observed). Changing the B-value away from the equilibrium value does mean that you are no longer sampling at equilibrium. This approach of simulating at multiple B-values is generally used to estimate the relative stability of water networks.

If you simply want to favour insertion moves to speed up the hydration of a water network for example then the only way to do this (assuming you still want to observe equilibrium behaviour) is to play around with the code to allow insertion moves to be attempted with greater frequency and for this effect to be accounted for in the acceptance criteria. Even then, it may not have the desired effect given the decrease in acceptance probabilities.

Hopefully this is useful, please let me know if any further questions.

Thanks,

Ollie

**Comment by olliemelling** [comment]
@qyuan7 are you happy for this issue to now be closed?
